"""empty message

Revision ID: 6d34e3ede70a
Revises: 48377414b59b
Create Date: 2023-01-14 22:23:28.543864

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '6d34e3ede70a'
down_revision = '48377414b59b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "invoices",
        sa.Column("enable_downloads", sa.Boolean(), nullable=True, default=False),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("invoices", "enable_downloads")

    # ### end Alembic commands ###
